### PR TITLE
connect_inbo_dbase(): also support ODBC Driver version 18 *

### PR DESCRIPTION
**Pull request by florisvdh**
Before driver version 18, connection string parameter 'Encrypt' was supposed 'no' by default. Since driver version 18, this has become 'yes'; however for us that is unneeded and it brings along another complexity, like the need to explicitly trust the server certificate. Therefore actively maintaining 'Encrypt=no' makes it work with version 18 the same way as with version 17.

More details are in the commit message.

Thanks @jo-loos for helping out!

@ElsLommelen I'm quite confident this should continue to work on Windows, but can you test it? Further, there is a failing check due to aspects not covered by this PR.

### CODE REVIEW

**Comment by ElsLommelen** [comment]
Can you please add a short explanation on NEWS.md (and update the version number)?
The error probably has to do with a new version of checklist, I'll have a look at it next Monday (and take the opportunity of a new version to fix some additional minor issues).

**Comment by ElsLommelen** [comment]
It works fine on Windows, just have a look at PR #44  to finish this PR.

**Comment by florisvdh** [comment]
Thank you @ElsLommelen for preparing these tasks already. A (very) minor update of the NEWS item is suggested in c525f88.

**Review by ElsLommelen — APPROVED** [review]
Thank you very much to fix this, @florisvdh !

**Pull request merged**
