### PR TITLE
Readme: small markdown fix

### PR DESCRIPTION
**Pull request by florisvdh**

### CODE REVIEW

**Comment by florisvdh** [comment]
Hm, wait, I'll add the updated website as well (where I noticed it). Long live automation :wink:

**Review by ElsLommelen — APPROVED** [review]
Thanks!

**Comment by florisvdh** [comment]
@ElsLommelen I was just in the course of fixing all this, and that's now done. Shall I force update this branch?

**Comment by florisvdh** [comment]
Note following results of `R CMD check`:

```
── R CMD check results ────────────────────────────────── inbodb 0.0.0.9000 ────
Duration: 31s

> checking for missing documentation entries ... WARNING
  Undocumented S4 methods:
    generic 'dbDisconnect' and siglist 'OdbcConnection'
    generic 'dbFetch' and siglist 'OdbcResult'
  All user-level objects in a package (including S4 classes and methods)
  should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

> checking dependencies in R code ... NOTE
  package 'methods' is used but not declared

0 errors ✓ | 1 warning x | 1 note x
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.
```

**Comment by ElsLommelen** [comment]
I hesitated to show the documentation for these adapted methods from other classes, but now I added it.

**Pull request merged**
