### PR TITLE
Inboveg patches hvc

### PR DESCRIPTION
**Pull request by hansvancalster**
@ElsLommelen this PR contains some patches to make PR #13 work and updates the vignette and some of the functions.
However, when I do `devtools::check()` , there is one warning when rebuilding the newly added vignette about 'missing package dbplyr needed for database backends' which I couldn't solve.  Can you have a look?

@ElsDeBie I think that when this branch is merged in your branch, your PR #13 will be ready. I am postponing review until this one is merged in your branch.

### CODE REVIEW

**Comment by ElsLommelen** [comment]
@hansvancalster I see several problems (before checking your changes into detail):
- the newly added vignette requires access to inboveg, which means that users can only install the package including the vignettes if and when they have access to inboveg.  Same problem will occur when the package website will be build using pkgdown...  So consider only adding the R code to the vignette, using eval = FALSE.  (You could test for a connection and run the code if the connection to inboveg can be made, but on the website the vignette will be without evaluation anyway...)
- in some of the `get_inboveg`-functions, methods `collect`, `tbl` and `sql` are imported from `dplyr`, but for databases the `dbplyr` methods should be used.  Don't forget to add `dbplyr` to the dependencies in the description file as well.  (All examples are marked as 'don't run', but to check if this problem is solved, it seems a good idea to take away one of these marks temporary while doing a local check.  Or otherwise you could solve this problem before changing the vignette...)

I haven't tested it, but I suppose the latter will solve your problem?  Honestly, I haven't checked your changes yet, I will have a closer look at them after the problem is solved.

(Also: I'm not sure how you constructed this branch and PR, but I would recommend merging the branch of #13 in this branch before merging the PR (locally by using `git merge update_inboveg`) and solve conflicts.)

**Comment by florisvdh** [comment]
> So consider only adding the R code to the vignette, using eval = FALSE.

In the watina package some hardcoded, commented output has been included for this reason. Of course, this has an obvious burden on maintenance, but it works. [Example](https://inbo.github.io/watina/articles/v110_xg3.html) (see also general note at the top).

**Comment by ElsLommelen** [comment]
Good idea!  For maintenance reasons, I would recommend @hansvancalster and @ElsDeBie to carefully consider where output is needed and not add it anywhere.  ;-)
(Generally users that want to use these functions, have access to inboveg, so they can easily copy and test code from the vignette on the website.  I would only add output if the vignette focuses on the output of the function.)

**Comment by hansvancalster** [comment]
Done! No warnings, errors or notes.

**Pull request merged**
