### PR TITLE
Characters

### LINKED ISSUE #2: problems with UTF-8 characters in Windows
Some UTF-8-characters retrieved from SQL Server databases are not correctly shown in Windows.  This problem could be solved similar to `collect()` in the watina package, but it should be solved in such way that it works for both `odbc::dbGetQuery()` and `dbplyr`.

### PR DESCRIPTION
**Pull request by ElsLommelen**
This PR adds the function convertdf_enc from package [watina](https://github.com/inbo/watina) and changes dbFetch to reduce encoding problems in Windows.  This assures all characters are interpreted correctly, which means
- they are presented correctly if results from queries are saved in text files, tables or reports (.csv, .pdf, .html,...).
- they are handled correctly in text operations such as grepl()
- they are sometimes shown correctly in RStudio but not always, as the way they are presented in RStudio, depends on the locale (nicely presented in [this conversation](https://community.rstudio.com/t/rstudio-ide-inconsistently-displaying-some-characters/5135/3)).

As the locale should be set/changed in .Rprofile, it is impossible to capture this in our package code.  If desired to change this on an organisational level, it should be solved in the installation instructions.  Another option is to add a vignet with a manual to change this.  Any opinions about this?

fixes #2

### CODE REVIEW

**Review by florisvdh — CHANGES_REQUESTED** [review]
@ElsLommelen Highly interesting, your implementation in `dbFetch()`! :+1: Does this also affect `collect()`? That would be great!

You still implement an older version of `convertdf_enc()`. See inbo/watina#45: in the `watina` release candidate, it is reexported from `inborutils` - but I could do that from `inbodb` as well :wink:). In `inborutils`, it has been further elaborated (inbo/inborutils#68) - maybe this may even improve results (a `from` argument was added; necessary to cope with a shapefile case). Hence, best use the version at https://github.com/inbo/inborutils/blob/master/R/encode_df_sf.R.

**Comment by ElsLommelen** [comment]
`dbFetch()` is the central method that fetches data from a database, which is used by both `tbl()` and `dbGetQuery()`, which means changes should be done there to affect both use of DBI/odbc and dbplyr.
I'll copy the new version and I'll merge the new changes from the master as well.

**Review by florisvdh — APPROVED** [review]
Thanks @ElsLommelen 

Are the `pkgdown.css` etc updates due to your `pkgdown` upgrading? Anyway, at a future time where this is all transferred to Travis (site deployment on gh-pages branch), `docs/` is better git-ignored in the master.

**Comment by florisvdh** [comment]
I just noted a list of conflicts in the message of fb93bf8, so best make sure they're gone

**Comment by ElsLommelen** [comment]
Yes, indeed, this is due to an upgrade of pkgdown.  I shouldn't have done this with 3 active branches.  Most of it was updated in the previous branch and already merged in the master, which makes the merge of the master to this branch a bit messy.
I think I did not push any conflicts?  I got some merge conflicts locally, but I solved them by rebuilding the site.
(Indeed, maybe I should check to setup some CI.)

**Review by hansvancalster — APPROVED** [review]
Nice work! I only looked at diffs, nothing tested....

**Pull request merged**
