### PR TITLE
Update inboveg

### PR DESCRIPTION
**Pull request by ElsDeBie**
added a vignette for inboveg-functions

### CODE REVIEW

**Review by hansvancalster — COMMENTED** [review]
Everything looks fine to me - at least from a technical  point of view. 
@ElsDeBie can you have a look at the vignette one more time? One thing I noticed is that there is a lot of repetition. Some suggestions:

- remove the ### Example subtitles - they are not necessary
- rephrase repeatedly copy-pasted sentences in different ways which will make the vignette more readable (I have done this already in some places but not all)
- consider revising the order in which you introduce each of the functions: maybe better to show header info before getting the recordings themselves. Think of a typical workflow where you would first want to know info about a survey, next metadata about relevés in that survey, then the data themselves (classifications and recordings of species, relationships between recordings)?

**Comment by ElsDeBie** [comment]
Euh, het is weeral even geleden, maar hoe vraag ik review aan ?

**Review by hansvancalster — APPROVED** [review]
Thanks @ElsDeBie :+1: . I think this is ready now and can be merged!

**Comment by ElsLommelen** [comment]
@hansvancalster eventjes wachten, ik merkte gisteren dat die website nog manueel gebouwd moet worden, ik maak het straks nog wel even in orde en voer dan de merge uit.

**Comment by hansvancalster** [comment]
OK, will leave merging to you @ElsLommelen

**Pull request merged**
